openapi: 3.0.0
info:
  title: Example
  version: 1.0.0
servers:
  - url: 'https://my-json-server.typicode.com/galrito/kiota-deserializer-php-bug-example'
paths:
  /products:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
    schemas:
        Product:
          type: object
          properties:
              id:
                  type: integer
              name:
                  type: string
              price:
                  type: number
                  format: float
          required:
              - id
              - name
              - price